name: Cypress CI Tests using start-server-and-test

on:
  # Manual button click from the GitHub UI
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: NPM Install
      #   run: npm ci

      - name: Install Start Server and Test
        run: npm install start-server-and-test --no-save

      - name: Run Application and Cypress E2E Tests
        run: npx start-server-and-test start http://localhost:3000 cypress:run

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Cypress videos
          path: cypress/videos
